SET search_path to health;

SELECT DISTINCT
    d.name AS doctor_name,
    h.name AS hospital_name,
    dep.name AS department_name
FROM hospitaldoctor hd
JOIN doctor d ON hd.doctor_id = d.doctor_id 
JOIN hospital h ON hd.hospital_id = h.hospital_id 
JOIN departmentdoctor dd ON d.doctor_id = dd.doctor_id  
JOIN department dep ON dd.department_id = dep.department_id  
JOIN hospitaldepartment hdpt ON h.hospital_id = hdpt.hospital_id 
ORDER BY doctor_name, hospital_name;


