SET
    search_path TO ezecream_05;

-- cleans the table and resets the autogenerated pk value
TRUNCATE TABLE orders RESTART IDENTITY CASCADE;

INSERT INTO
    orders (customer_id, order_date)
VALUES
    (3, '2025-04-05'),
    (4, '2025-03-10'),
    (4, '2025-03-11'),
    (4, '2025-03-11');

SELECT
    *
FROM
    orders;

-- Tryingto get in Luca

-- INSERT INTO
-- ezecream_05.orders (
--     order_id,
--     customer_id,
--     order_date

--     )
-- VALUES
--     (5, 50, '2006-07-04');


