SET
    search_path TO ezecream_05;

-- cleans the table and resets the autogenerated pk value
TRUNCATE TABLE product RESTART IDENTITY CASCADE;

INSERT INTO
    product (name, price)
VALUES
     ('Piggelin', 15),
    ('Magnum Mandel', 30),
    ('Solero Twist', 25);

SELECT
    *
FROM
    product;